### ISSUE TITLE
UI Annoyance when reviewing tsumego

### ISSUE THREAD

**Issue by helion** [ligi/gobandroid#88]
This is for Gobandroid HD.

When I trigger an "unknown variation" notice the hint button disapears and the undo button shifts to fill the now empty space. Then, when I tap undo enough times to remove the notice, the hint button reapears pushing undo back to the left.  Because of  this I keep hitting the hint button when I want to keep undoing moves. Since the hint button pops up a modal box which requires my devices global back button to dismiss the accidental hits become very annoying. It basically breaks my focus on the tsumego and disrupts my train of thought every time it happens.

The first idea that jumps to my mind to of address the problem is to disable and grey out the hint button instead of removing it from the interface entirely.

**Comment by EdoPut** [comment]
I found this issue in v2.2.7 from the Fdroid store; currently using on a tablet.

I think the problem is in [ingame_tsumegu.xml][menu] because the number ordering in `android:orderInCategory` is undo first and then hint.

[menu]: https://github.com/ligi/gobandroid/blob/master/android/src/main/res/menu/ingame_tsumego.xml#L8
